---
# Port mailboxes from dreamhost to sovereign
# RUN THIS AFTER site.yml, BUT BEFORE LOGGING IN

- hosts: all
  user: deploy
  sudo: True
  vars_files:
    - vars/defaults.yml
    - vars/{{ 'testing' if testing is defined else 'user' }}.yml
  roles:
    - role: migration
      when: mail_migration is defined
